### ISSUE TITLE
Send snapshot update parameter 

### ISSUE THREAD

**Issue by andrebonna** [json-snapshot/json-snapshot.github.io#1]
Create a way to run tests with a 'update' flag to tell SnapshotFile to clear old data. (Same behavior as jest -u)

**Comment by malenkix** [comment]
Hi @andrebonna, thank you very much for this fine library. I love the idea to bring snapshot tests to the maven/java world. :)  I got 2 questions regarding this enhancement: Is there a reason this enhancement wasn't possible to achieve? What would be the current way to update failing snapshots? Should I just remove them after verification and rerun the tests?

**Comment by mayank-kapoor** [comment]
@andrebonna is the update snapshot functionality implemented yet ?  If not can we expect this in near future ?
