### ISSUE TITLE
Test method lookup fails when method has parameters

### ISSUE THREAD

**Issue by grimsa** [json-snapshot/json-snapshot.github.io#16]
This reproduces the problem:
```java
class TestX {

    @BeforeAll
    static void beforeAll() {
        SnapshotMatcher.start();
    }

    @AfterAll
    static void afterAll() {
        SnapshotMatcher.validateSnapshots();
    }

    @Test
    void testName() {
        testBasedOnArgs("a");
    }

    private void testBasedOnArgs(String arg) {
        expect(arg).toMatchSnapshot();
    }
}
```

Root cause: method name is taken from `StackTraceElement` and then used in lookup using `Class#getMethod()` or  `Class#getDeclaredMethod()`. However, if parameter types are not provided, method will not be found.

Solution could be to get all methods via `Class#getDeclaredMethods()` and then match method by name.

**Comment by andrebonna** [comment]
Fixed on version 1.0.17!
