### ISSUE TITLE
is this project alive?

### ISSUE THREAD

**Issue by zlymeda** [json-snapshot/json-snapshot.github.io#33]
Hi,

is this project still alive? 
I've noticed some outstanding PRs and no new releases.

Any help needed?

Thanks

**Comment by jasonCodesAway** [comment]
@andrebonna any chance @zlymeda or I or someone can help cut a new release?

**Comment by KostasKoyias** [comment]
@andrebonna @metas-ts @grimsa 

Are there any plans of releasing a new version that contains the [Introduce different matching modes](https://github.com/json-snapshot/json-snapshot.github.io/commit/863d2adecadc7d005918e0d152a1a8458d2117fc)?

That would help us a ton, not to rely on the order of the fields in the string representation of JSON response
Btw, very nice work on this one!

**Comment by maguro** [comment]
Ping

**Comment by maguro** [comment]
Hello!  @andrebonna has graciously added me to this project.  Many thanks!

**Comment by shahparth199730** [comment]
@andrebonna Any updates on when will be the next release taking place? It will be really helpful to have [Introduce different matching modes](https://github.com/json-snapshot/json-snapshot.github.io/commit/863d2adecadc7d005918e0d152a1a8458d2117fc) being present in the release.

**Comment by grimsa** [comment]
The company I work for is currently in the process of migrating to https://github.com/origin-energy/java-snapshot-testing which seems to be an a maintained fork of this project.

If this project is no longer actively maintained, it would probably be best to communicate it clearly and possibly endorse some actively maintained project as a replacement.
